language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.8.17
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.6
  - DJANGO_VERSION=1.11rc1
install:
  - pip install Django==$DJANGO_VERSION
  - pip install six
  - pip install -e .
script:
  - ./example/manage.py test formfield
branches:
  only:
    - master
