language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.7
  - DJAONG_VERSION=1.8
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -e .
script:
  - ./example/manage.py test formfield
branches:
  only:
    - master